name: zillow_mini
description: "Demo app for Tech Jobs USA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.0
  dio: ^5.3.2
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.0
  fpdart: ^1.1.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  infinite_scroll_pagination: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.7.0
  flutter_gen_runner: ^5.10.0
  mockito: ^5.4.6
  http_mock_adapter: ^0.6.1
  flutter_launcher_icons: "^0.14.4"

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - .env


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21



